debug: true
dns:
  server:
    addrs:
      - tcp://:53
      - udp://:53
    max_tcp_queries: -1
    read_timeout: 2s
    write_timeout: 2s
  client:
    addr: tcp://1.1.1.1:53
    dial_timeout: 2s
    read_timeout: 2s
    write_timeout: 2s
  observable_nets:
    - 127.0.0.0/24
    - 192.168.3.1/24
bgp:
  listen_port: 179
  listen_addrs: []
  router_id: 1.3.3.7
  router_asn: 65543
  peer_asn: 65542
  peer_nets:
    - 0.0.0.0/0
    - ::/0
  next_hop_v4: 10.8.2.1
  next_hop_v6: fd41:ce44:b4c9:44ca::1
checker:
  direct_dev: wlan0
  vpn_dev: eu
  concurrency: 32
  queue_size: 1024
  ip_history_size: 32384
  ip_history_ttl: 10m0s
  decisions_size: 129536
  decisions_ttl: 30m0s
